#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e6c0e1b2-67ff-45b6-971e-cf28d281a1b6 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temperature2;
  CloudLight led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "thingProperties.h"
#include <Wire.h>
#include <Adafruit_BMP085.h>

Adafruit_BMP085 bmp;
int ledPin  = 23;
int state = 0;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  if (!bmp.begin()) {
	Serial.println("Could not find a valid BMP085/BMP180 sensor, check wiring!");
	while (1) {}
  }
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  pinMode(ledPin, OUTPUT);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
}

void loop() {
  ArduinoCloud.update();
  temperature2 = bmp.readTemperature();
  if(temperature2 < 0 || temperature2 > 50){
    led = 1;
    state = 1;
    digitalWrite(ledPin, HIGH);
  }
  else{
    led = 0;
    state = 0;
  }
  
}


/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  {
  if(led == 0 && (temperature2>=0 && temperature2<=50) && state==0){
    digitalWrite(ledPin, HIGH);
    Serial.println(temperature2);
  }
  else{
    digitalWrite(ledPin, LOW);
  }

}


/*
  Since Temperature2 is READ_WRITE variable, onTemperature2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperature2Change()  {
  // Add your code here to act upon Temperature2 change
  if(temperature2 < 0|| temperature2 > 50){
     digitalWrite(ledPin, HIGH);
    Serial.println("Led off");
  
}
}